# Generated by Django 4.1.3 on 2022-12-05 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UnitDatasheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('movement', models.IntegerField()),
                ('weapon_skill', models.IntegerField()),
                ('ballistic_skill', models.IntegerField()),
                ('strength', models.IntegerField()),
                ('toughness', models.IntegerField()),
                ('wounds', models.IntegerField()),
                ('attacks', models.IntegerField()),
                ('leadership', models.IntegerField()),
                ('save', models.IntegerField()),
                ('abilities', models.CharField(max_length=500)),
                ('point_value', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Wargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('range', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('strength', models.IntegerField()),
                ('armor_penetration', models.IntegerField()),
                ('damage', models.IntegerField()),
                ('abilities', models.CharField(max_length=500)),
                ('point_value', models.IntegerField()),
            ],
        ),
    ]
