# Generated by Django 4.1.3 on 2022-12-05 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdatasheet',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
