# Generated by Django 4.1.3 on 2022-12-05 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0002_unitdatasheet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdatasheet',
            name='role',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
