# Generated by Django 4.1.3 on 2022-12-05 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0003_unitdatasheet_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitdatasheet',
            name='save',
        ),
        migrations.AddField(
            model_name='unitdatasheet',
            name='armor_save',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
