# Generated by Django 4.1.3 on 2022-12-12 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0005_optionalwargear'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionalWargear',
        ),
    ]
