# Generated by Django 4.1.3 on 2022-12-12 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0007_optionalwargear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionalwargear',
            old_name='unit',
            new_name='imperial_knight_unit',
        ),
    ]
