# Generated by Django 4.1.3 on 2022-12-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0008_rename_unit_optionalwargear_imperial_knight_unit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='optionalwargear',
            old_name='imperial_knight_unit',
            new_name='unit',
        ),
    ]
