# Generated by Django 4.1.3 on 2022-12-12 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0009_rename_imperial_knight_unit_optionalwargear_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optionalwargear',
            name='unit',
        ),
        migrations.AddField(
            model_name='optionalwargear',
            name='imperial_knight_unit',
            field=models.ManyToManyField(related_name='optional_wargear', to='list_fabricator_app.unitdatasheet'),
        ),
    ]
