# Generated by Django 4.1.3 on 2022-12-12 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0010_remove_optionalwargear_unit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitdatasheet',
            name='wargear',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
