# Generated by Django 4.1.3 on 2022-12-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0012_alter_wargear_damage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unitdatasheet',
            name='wargear',
        ),
        migrations.CreateModel(
            name='FixedWargear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weapon', models.CharField(max_length=100)),
                ('imperial_knight_unit', models.ManyToManyField(related_name='wargear', to='list_fabricator_app.unitdatasheet')),
            ],
        ),
    ]
