# Generated by Django 4.1.3 on 2022-12-12 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0013_remove_unitdatasheet_wargear_fixedwargear'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixedwargear',
            old_name='weapon',
            new_name='fixed_weapon',
        ),
    ]
