# Generated by Django 4.1.3 on 2022-12-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_fabricator_app', '0014_rename_weapon_fixedwargear_fixed_weapon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wargear',
            name='range',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wargear',
            name='strength',
            field=models.CharField(max_length=100),
        ),
    ]
